#!/bin/bash

set -eu

if [ $# -ne 2 ]
then
    echo "Please specify action (build, push, refresh, run, scan) and platform, e.g. 'ubuntu/22.04'!"
    exit 1
fi

MATCH=0
echo "${2}" | grep -E '^[[:alnum:]]+/[[:alnum:]]+\.*[[:alnum:]]*/*$' > /dev/null && MATCH=1
if [ ${MATCH} -ne 1 ]
then
    echo "Invalid platform format! Specify distro and release, separated by slash, e.g. 'ubuntu/22.04'."
    exit 2
fi

export PLATFORM=$(echo ${2} | cut -d'/' -f1)
# Ensure we trim any trailing slashes
export RELEASE=$(echo ${2} | cut -d'/' -f2 | sed 's@/*$@@')

if [ ! -f "${PLATFORM}/${RELEASE}/Dockerfile" ]
then
    echo 'Dockerfile not found! Please check if the specified platform is correct.'
    exit 4
fi

function find_exec ()
{
    RET=0
    podman --version &> /dev/null && RET=1 || true

    if [ ${RET} -eq 1 ]
    then
        echo 'podman'
    else
        RET=0
        docker --version &> /dev/null && RET=1 || true

        if [ ${RET} -eq 1 ]
        then
            echo 'docker'
        else
            echo ''
        fi
    fi
}

function as_build ()
{
    docker build --no-cache --pull --tag "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}" "${2}"
}

function as_push ()
{
    docker push "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}"
}

function as_scan ()
{
    docker scout quickview "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}"
}

function as_run ()
{
    # Determine container solution
    export exec=$(find_exec)
    # Fire up instance
    CONT_ID=$(${exec} run --rm --detach "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}")
    # Don't exit the container if errors occur
    set +e
    # Let us check stuff before exiting
    ${exec} exec -it "${CONT_ID}" bash
    # Stop instance
    ${exec} stop "${CONT_ID}"
}

case "$1" in
    build)
        as_build "${@}"
        ;;

    push)
        as_push "${@}"
        ;;

    scan)
        as_push "${@}"
        ;;

    refresh)
        as_scan "${@}"
        as_build "${@}"
        as_scan "${@}"
        as_push "${@}"
        ;;

    run)
        as_run "${@}"
        ;;

    *)
        echo "Invalid action! Valid actions are: build, push, refresh, run, scan."
        exit 3
        ;;
esac
