#!/bin/bash

set -eu

function check_platform ()
{
    MATCH=0
    echo "${1}" | grep -E '^[[:alnum:]]+/[[:alnum:]]+\.*[[:alnum:]]*/*$' > /dev/null && MATCH=1
    if [ ${MATCH} -ne 1 ]
    then
        echo "Invalid platform format! Specify distro and release, separated by slash, e.g. 'ubuntu/22.04'."
        exit 2
    fi

    export PLATFORM=$(echo ${1} | cut -d'/' -f1)
    # Ensure we trim any trailing slashes
    export RELEASE=$(echo ${1} | cut -d'/' -f2 | sed 's@/*$@@')

    if [ ! -f "${PLATFORM}/${RELEASE}/Dockerfile" ]
    then
        echo 'Dockerfile not found! Please check if the specified platform is correct.'
        exit 4
    fi
}

function set_podman_aliases ()
{
    mkdir -p "${HOME}/.config/containers/registries.conf.d"
    cat << EOF > "${HOME}/.config/containers/registries.conf.d/bviktor.conf"
[aliases]
  "bviktor/ansible-systemd-almalinux" = "docker.io/bviktor/ansible-systemd-almalinux"
  "bviktor/ansible-systemd-archlinux" = "docker.io/bviktor/ansible-systemd-archlinux"
  "bviktor/ansible-systemd-fedora" = "docker.io/bviktor/ansible-systemd-fedora"
  "bviktor/ansible-systemd-lint" = "docker.io/bviktor/ansible-systemd-lint"
  "bviktor/ansible-systemd-ubuntu" = "docker.io/bviktor/ansible-systemd-ubuntu"
  "archlinux" = "docker.io/archlinux"
EOF
}

function find_exec ()
{
    RET=0
    podman --version &> /dev/null && RET=1 || true

    if [ ${RET} -eq 1 ]
    then
        set_podman_aliases
        echo 'podman'
    else
        RET=0
        docker --version &> /dev/null && RET=1 || true

        if [ ${RET} -eq 1 ]
        then
            echo 'docker'
        else
            echo ''
        fi
    fi
}

function as_build ()
{
    ${exec} build --no-cache --pull --tag "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}" "${1}"
}

function as_push ()
{
    ${exec} push "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}"
}

function as_scan ()
{
    if [ "${exec}" == 'docker' ]
    then
        ${exec} scout quickview "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}"
    else
        echo "Scan is unsupported with podman, skipping..."
    fi
}

function as_run ()
{
    # Fire up instance
    CONT_ID=$(${exec} run --rm --detach "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}")
    # Don't exit the container if errors occur
    set +e
    # Let us check stuff before exiting
    ${exec} exec -it "${CONT_ID}" bash
    # Stop instance
    ${exec} stop "${CONT_ID}"
}

function as_refresh ()
{
    as_scan
    as_build "${1}"
    as_scan
    as_push
}

function as_refresh_all ()
{
    readarray -t all_platforms < <(ls -d */*)

    for (( i=0; i<${#all_platforms[@]}; i++ ));
    do
        echo "Updating ${all_platforms[$i]} ..."
        check_platform "${all_platforms[$i]}"
        as_refresh "${all_platforms[$i]}"
    done
}

if [ $# -ne 1 ] && [ $# -ne 2 ]
then
    echo "Please specify action (build, push, refresh, refresh-all, run, scan) and platform, e.g. 'ubuntu/22.04'!"
    exit 1
fi

if [ $# -eq 1 ] && [ "$1" != 'refresh-all' ]
then
    echo "Invalid action!"
    exit 1
fi

if [ $# -eq 2 ]
then
    check_platform "${2}"
fi

# Determine container solution
export exec=$(find_exec)

case "$1" in
    build)
        as_build "${2}"
        ;;

    push)
        as_push
        ;;

    scan)
        as_scan
        ;;

    refresh)
        as_refresh "${2}"
        ;;

    refresh-all)
        as_refresh_all
        ;;

    run)
        as_run
        ;;

    *)
        echo "Invalid action! Valid actions are: build, push, refresh, refresh-all, run, scan."
        exit 3
        ;;
esac
